Ответ:
Переменной был присвоен результат - Infinity.
Исключение типа ArithmeticException срабатывают только при условии, что данные представляют целое число.